services:
  - name: mongo:4.2
    alias: mongo
  - name: rabbitmq:management
    alias: rabbitmq

stages:
  - test
  - build
  - publish
  - release

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_DEFAULT_VHOST: doclib
  MONGO_PORT: 27017
  RABBITMQ_PORT: 5672

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  untracked: false
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

default:
  image: registry.gitlab.com/medicines-discovery-catapult/informatics/docker-images/ci/sbt:latest

test:
  stage: test
  variables:
    MONGO_HOST: mongo
    MONGO_DATABASE: leadmine-test
    MONGO_COLLECTION: documents
    MONGO_USERNAME: admin
    MONGO_PASSWORD: admin
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_USERNAME: guest
    RABBITMQ_PASSWORD: guest
    RABBITMQ_VHOST: doclib
  script:
    - sleep 20
    - curl http://guest:guest@rabbitmq:15672/api/overview
    - sbt clean coverage test it/test coverageReport
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - target/scala-2.13/scoverage-report/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

assemble:
  stage: build
  script:
    - sbt assembly
  artifacts:
    paths:
      - target/scala-2.13/consumer.jar
  except:
    refs:
      - main
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --build-arg VERSION=$CI_COMMIT_REF_SLUG
      --build-arg VERSION_HASH=$CI_COMMIT_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  except:
    refs:
      - main
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: release
  script:
    - cictl exec release sbt
  only:
    - main
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

assemble-main:
  stage: build
  script:
    - sbt assembly
  artifacts:
    paths:
      - target/scala-2.13/consumer.jar
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-main:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
  script:
    - >
      /kaniko/executor --context $CI_PROJECT_DIR
      --build-arg VERSION=$CI_COMMIT_REF_NAME
      --build-arg VERSION_HASH=$CI_COMMIT_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
